sonar.projectKey=shopping-cart
sonar.projectName=shopping-cart
sonar.projectVersion=1.0

sonar.sources=.

sonar.java.binaries=target

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=src/test/**
sonar.coverage.exclusions=**/ShoppingCartController.java, **/ShoppingCartApp.java
sonar.host.url=http://localhost:9000
